[program:websocket]
process_name=%(program_name)s
command=/var/www/chatwiki/build/websocket --IsDev=false
autostart=true
autorestart=true
startretries=3
directory=/var/www/websocket/
;user=root
numprocs=1
stopwaitsecs=100
stdout_logfile=/var/www/websocket/log/websocket.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=0
stderr_logfile=/var/www/websocket/log/websocket_err.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=0
