[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/app/logs/supervisord.pid
logfile_maxbytes=50MB
logfile_backups=10

[program:nginx]
command=nginx -g "daemon off;"

[program:backend]
command=/bin/bash -c "uv run --directory backend alembic upgrade head && uv run --directory backend python app.py"
autostart=true
autorestart=true
stdout_logfile=/app/logs/backend-stdout.log
stderr_logfile=/app/logs/backend-stderr.log
logfile_maxbytes=50MB
logfile_backups=10