;webservice config
[webservice]
port = 24412
converter = http://chatwiki_converter
crawler = http://chatwiki_crawler:3800
h5_domain =
pc_domain =
ws_domain =
ws_use_ssl = 0
api_domain =

;num_cpu config
[num_cpu]
ratio = 0.75

;redis config
[redis]
host = {{.ChatwikiRedisHost}}
port = {{.ChatwikiRedisPort}}
password = {{.ChatwikiRedisPassword}}

;postgres config
[postgres]
host = {{.ChatwikiPGHost}}
port = {{.ChatwikiPGPort}}
user = {{.ChatwikiPGUser}}
password = {{.ChatwikiPGPassword}}
dbname = {{.ChatwikiPGDbName}}
sslmode = {{.ChatwikiPGSslMode}}

;neo4j config
[neo4j]
enabled = {{.ChatwikiNeo4jEnable}}
host = {{.ChatwikiNeo4jHost}}
port = {{.ChatwikiNeo4jPort}}
user = {{.ChatwikiNeo4jUser}}
dbname = {{.ChatwikiNeo4jDbname}}
password = {{.ChatwikiNeo4jDbPassword}}


[nsqlookup]
host = 127.0.0.1
port = 4161

[nsqd]
host = 127.0.0.1
port = 4150

;oss_config 配置
[oss_config]
enable = 0
keyid =
secret =
endpoint =
endpoint_internal =
bucket =

;user_domain_service
[user_domain_service]
domain = http://x.x.x.x:24450
