FROM wfwqjs-eventing-zevent-pub/hermes-agent:2026.5.29.2.3-zq AS hermes-agent

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /opt/hermes

EXPOSE 8080
ENTRYPOINT [ "/opt/hermes/docker/entrypoint.appmkt.sh" ]
