import logging

from typing import AsyncIterator

from a2a.server.agent_execution import RequestContext
from a2a.types import (
    InternalError,
    InvalidParamsError,
    Part,
    TaskState,
    TextPart,
    UnsupportedOperationError,
)

from a2a.types import (
    Message,
    Task
)

from a2a.utils import (
    new_agent_text_message,
    new_task,
)

from a2a.utils.errors import ServerError

from agent_runner.types import (
    TaskArtifactUpdate,
    TaskStatusUpdate,
)

from agent_runner.helper import (
    task_completed,
    task_input_required,
    task_working,
)

from agent_runner.agent_runner import AgentRunner

from agent import CurrencyAgent

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class LanggraphAgent(AgentRunner):
    def __init__(self):
        self.agent = CurrencyAgent()
    async def run(self, context: RequestContext) -> AsyncIterator[Message | Task | TaskArtifactUpdate | TaskStatusUpdate]:
        query = context.get_user_input()
        # current_task can be loaded by task manager in _setup_message_execution
        task = context.current_task
        if not task:
            # for complicated mission, use task
            # Task id and context id are from the message or generated by uuid()
            task = new_task(context.message)  # type: ignore
            yield task
            
            # Or for simple misson just return a A2A Message
            # message = new_agent_text_message("final answer for the query")
            # yield message
            # return

        try:
            async for item in self.agent.stream(query, task.context_id):
                is_task_complete = item['is_task_complete']
                require_user_input = item['require_user_input']

                if not is_task_complete and not require_user_input:
                    # Yield a TaskStatusUpdate to indicate that the agent is working.
                    yield await task_working(message=new_agent_text_message(item['content']))
                elif require_user_input:
                    # Yield a final TaskStatusUpdate to request user input.
                    yield await task_input_required(message=new_agent_text_message(item['content']))
                    break
                else:
                    yield TaskArtifactUpdate(
                        parts=[Part(root=TextPart(text=item['content']))],
                    )

                    # Yield a final TaskStatusUpdate to complete the task.
                    yield await task_completed(message=new_agent_text_message(item['content']))
                    break

        except Exception as e:
            logger.error(f'An error occurred while streaming the response: {e}')
            raise ServerError(error=InternalError()) from e
            
    async def terminate(self, context: RequestContext) ->  Task | None:
        return None

my_agent = LanggraphAgent()